kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-example
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example-nginx
      type: demo-02
  template:
    metadata:
      name: pod-example
      labels:
        app: example-nginx
        type: demo-02
    spec:
      containers:
        - name: container-example
          image: nginx
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
          ports:
            - containerPort: 80
