apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fastapi-demo
type: Opaque
data:
  POSTGRES_USER: ZmFzdGFwaQ==        # "fastapi" encodé en base64
  POSTGRES_PASSWORD: ZmFzdGFwaQ==    # "fastapi" encodé en base64
  POSTGRES_DB: ZmFzdGFwaV9kZW1v      # "fastapi_demo" encodé en base64
