kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-example
spec:
  replicas: 10
  selector:
    matchLabels: {{ include "demo-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- /* Le nom du pod */}}
      name: {{ .Release.Name }}-{{ .Chart.Name }}-pod
      labels: {{ include "demo-nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-container
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          resources:
            limits:
              cpu: "500m"
              memory: "200Mi"
            requests:
              cpu: "500m"
              memory: "200Mi"
          ports: {{ .Values.containerPorts | toYaml | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 20
