{{- include "demo-nginx.validateTestValidation" . -}}
{{- include "demo-nginx.validateTestValidationCorrectValue" . -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-example
spec:
  replicas: 10
  selector:
    matchLabels: {{ include "demo-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- /* Le nom du pod */}}
      name: {{ .Release.Name }}-{{ .Chart.Name }}-pod
      labels: {{ include "demo-nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-container
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          {{ if hasKey .Values.infos.deployment "resources" -}}
          resources:
            limits:
              {{ with .Values.infos.deployment.resources.limits -}}
              cpu: {{ .cpu }}
              memory: {{ .memory}}
              {{- end }}
            requests:
              {{ with .Values.infos.deployment.resources.requests -}}
              cpu: {{ .cpu }}
              memory: {{ .memory}}
              {{- end }}
          {{- end }}
          ports: {{ .Values.containerPorts | toYaml | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 20
