{{ if .Values.service.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: service-example
spec:
  type: LoadBalancer
  selector:
    app: example-nginx
    type: demo-02
  ports:
    - targetPort: 80
      port: 80
{{- end }}